controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_controller:
      type: diff_drive_controller/DiffDriveController
      parameters:
        left_wheel_names: 
          - "front_left_wheel_joint"
          - "rear_left_wheel_joint"
        right_wheel_names: 
          - "front_right_wheel_joint"
          - "rear_right_wheel_joint"
        wheel_separation: 0.65
        wheel_radius: 0.1
        odom_frame_id: odom
        base_frame_id: base_link
        publish_rate: 50.0
        enable_odom_tf: true